server:
  port: 8080

spring:
  application:
    name: oriente-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/oriente_db
    username: oriente_user
    password: oriente_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:OrienteSecretKeyForTCCProject2025VerySecureKey123}
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# Logging
logging:
  level:
    com.oriente: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE